config/routes.rb
Rails.application.routes.draw do
  get 'store/index'

  resources :items

  root 'store#index'

  #api routes

  get '/api/items' => 'store#show'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/item.rb
class Item < ApplicationRecord
    validates :name, presence: true,
                     length: { minimum: 2 }

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
    def index
        @items = Item.all
    end

    def new
        @item = Item.new
    end

    def show
        @item = Item.find(params[:id])
    end

    def create
        @item = Item.new(item_params)

        if @item.save
            redirect_to @item
        else
            render 'new'
        end
    end
end

private
    def item_params
        params.require(:item).permit(:name, :price, :description)
    end

app/controllers/store_controller.rb
class StoreController < ApplicationController
  def index
      @items = Item.all
  end
  
  def show
    items = Item.all
    render :json => items.to_json
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/store_helper.rb
module StoreHelper
end

app/views/items/index.html.erb
<div class="mdl-grid">
    <h4>Products</h4>
</div>
<div class="mdl-grid">
    <table class="mdl-data-table mdl-js-data-table mdl-shadow--2dp">
    <tr>
        <th class="mdl-data-table__cell--non-numeric">Name</th>
        <th>Price</th>
        <th>Description</th>
        <th></th>
    </tr>
    
    <% @items.each do |item| %>
        <tr>
            <td class="mdl-data-table__cell--non-numeric"><%= item.name %></td>
            <td><%= number_to_currency(item.price, :locale => :gb) %></td>
            <td><%= item.description %></td>
            <td><%= link_to 'View', item_path(item) %></td>
        </tr>
    <% end %>
    </table>
</div>

app/views/items/new.html.erb
<h4>Add new item to store</h4>
<div class="mdl-grid">
  <%= form_with scope: :item, url: items_path, local: true do |form| %>

      <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label">   
          <%= form.text_field :name, class: 'mdl-textfield__input' %>
          <%= form.label :name, class: 'mdl-textfield__label' %>
      </div>
      <br />
      <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label">
          <%= form.text_field :price, class: 'mdl-textfield__input', pattern:'-?[0-9]*(\.[0-9]+)?' %>
          <%= form.label :price, class: 'mdl-textfield__label' %>
          <span class="mdl-textfield__error">Input is not a number!</span>
      </div>
      <br />
      <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label">
          <%= form.text_area :description, class: 'mdl-textfield__input' %>
          <%= form.label :description, class: 'mdl-textfield__label' %>
      </div>
      <br />
      <%= form.submit 'Add item', :class => 'mdl-button mdl-js-button mdl-button--raised mdl-js-ripple-effect mdl-button--accent' %>

  <% end %>
</div>

app/views/items/show.html.erb
<h4>Item info: <%= @item.name %></h4>
<div class="mdl-grid">
    <ul class="mdl-list">
        <li class="mdl-list__item">
            <strong>Name:&nbsp;</strong>
            <%= @item.name %>
        </li>

        <li class="mdl-list__item">
            <strong>Price:&nbsp;</strong>
            £<%= @item.price %>
        </li> 

        <li class="mdl-list__item">
            <strong>Description:&nbsp;</strong>
            <%= @item.description %>
        </li>
    </ul>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ESI Example</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <!-- Always shows a header, even in smaller screens. -->
    <div class="mdl-layout mdl-js-layout mdl-layout--fixed-header">
      <header class="mdl-layout__header">
        <div class="mdl-layout__header-row">
          <!-- Title -->
          <span class="mdl-layout-title">Will's less than impressive emporium</span>
          <!-- Add spacer, to align navigation to the right -->
          <div class="mdl-layout-spacer"></div>
          <!-- Navigation. We hide it in small screens. -->
          <nav class="mdl-navigation">
              <%= link_to 'View all items', items_path, class: 'mdl-navigation__link' %>
          </nav>
          <nav class="mdl-navigation mdl-layout--large-screen-only">
              <%= link_to 'Add an item', new_item_path, class: 'mdl-navigation__link' %>
          </nav>
        </div>
      </header>
      <div class="mdl-layout__drawer">
        <span class="mdl-layout-title">Em - poor - ium</span>
        <nav class="mdl-navigation">
            <%= link_to 'View all items', items_path, class: 'mdl-navigation__link' %>
        </nav>
        <nav class="mdl-navigation">
            <%= link_to 'Add an item', new_item_path, class: 'mdl-navigation__link' %>
        </nav>
      </div>
      <main class="mdl-layout__content">
        <div class="page-content">
          <%= yield %>
        </div>
      </main>
    </div>

  </body>
</html>

app/views/store/index.html.erb
<div class="mdl-grid">
    <h4>Welcome</h4>
</div>
<div class="mdl-grid">
    <table class="mdl-data-table mdl-js-data-table mdl-shadow--2dp">
    <tr>
        <th class="mdl-data-table__cell--non-numeric">Name</th>
        <th>Price</th>
        <th>Description</th>
        <th></th>
    </tr>
    
    <% @items.each do |item| %>
        <tr>
            <td class="mdl-data-table__cell--non-numeric"><%= item.name %></td>
            <td><%= number_to_currency(item.price, :locale => :gb) %></td>
            <td><%= item.description %></td>
            <td><%= link_to 'View', item_path(item) %></td>
        </tr>
    <% end %>
    </table>
</div>